"""User model avatar add 2

Revision ID: d475fba5baf5
Revises: 990add02b7e9
Create Date: 2023-03-04 00:27:07.818457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd475fba5baf5'
down_revision = '990add02b7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=80), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
